### ISSUE TITLE
[BUG] Breaks with nvm-windows

### ISSUE THREAD

**Issue by vogloblinsky** [QingWei-Li/global-bin-path#1]
Using nvm-windows, nodejs 6.9.1, npm 3.10.8

The path returned is : undefined

The process.env.PATH is : C:\Program Files\nodejs

You want a PR or adding another test line 15 did the trick ?  ```|| path.basename(pathnames[i]) === 'nodejs'```

**Comment by QingWei-Li** [comment]
Yes, Contribution is welcome.

**Comment by QingWei-Li** [comment]
`v0.1.0` released.

**Comment by vogloblinsky** [comment]
Thanks
